In [1]:
import pandas as pd

# load excel file
df = pd.read_excel("Dataset_AI_Price_Engine.xlsx")

# convert to csv
df.to_csv("pricing_dataset.csv", index=False)

print("Conversion completed")

Conversion completed

In [2]:
df.head()

,date,product_id,product_name,quantity_sold,amazon_price,meesho_price,discount_pct,stock_quantity,rating,num_reviews,page_views,conversion_rate,demand_intensity,cost,profit
0,2024-05-10 00:00:00,P0010,SmartGen Headphones Plus,2,2236.79,2100.72,0.00,310,3.6,66,69,4.35,3.00,3601.50,872.08
1,2024-10-06 00:00:00,P0019,UrbanWear Shoes Premium,4,262.03,242.12,0.00,292,4.7,107,329,0.61,2.01,683.96,364.15
2,15-05-2024,P0022,StyleHub Shoes Pro,3,48.82,42.43,9.86,435,4.1,256,342,0.29,0.99,102.48,43.98
3,23-01-2025,P0006,TechPro Headphones Standard,1,2401.75,2196.13,0.00,375,4.1,117,174,0.57,0.99,1717.87,683.88
4,2024-03-04 00:00:00,P0047,StoryWorld Children Pro,5,50.58,45.79,0.00,448,4.7,366,357,0.28,1.00,189.90,62.99

In [3]:
df.columns

Index(['date', 'product_id', 'product_name', 'quantity_sold', 'amazon_price',
       'meesho_price', 'discount_pct', 'stock_quantity', 'rating',
       'num_reviews', 'page_views', 'conversion_rate', 'demand_intensity',
       'cost', 'profit'],
      dtype='object')

In [4]:
import numpy as np

In [5]:
df.isnull().sum()

date                0
product_id          0
product_name        0
quantity_sold       0
amazon_price        0
meesho_price        0
discount_pct        0
stock_quantity      0
rating              0
num_reviews         0
page_views          0
conversion_rate     0
demand_intensity    0
cost                0
profit              0
dtype: int64

In [6]:
df = df.drop(columns=[
    'product_id',
    'cost',
    'profit',
    'stock_quantity'
])

In [7]:
df.columns

Index(['date', 'product_name', 'quantity_sold', 'amazon_price', 'meesho_price',
       'discount_pct', 'rating', 'num_reviews', 'page_views',
       'conversion_rate', 'demand_intensity'],
      dtype='object')

In [8]:
df['amazon_price'] = pd.to_numeric(df['amazon_price'], errors='coerce')
df['meesho_price'] = pd.to_numeric(df['meesho_price'], errors='coerce')
df['rating'] = pd.to_numeric(df['rating'], errors='coerce')

In [9]:
df['price_difference'] = df['amazon_price'] - df['meesho_price']

In [10]:
df.head()

,date,product_name,quantity_sold,amazon_price,meesho_price,discount_pct,rating,num_reviews,page_views,conversion_rate,demand_intensity,price_difference
0,2024-05-10 00:00:00,SmartGen Headphones Plus,2,2236.79,2100.72,0.00,3.6,66,69,4.35,3.00,136.07
1,2024-10-06 00:00:00,UrbanWear Shoes Premium,4,262.03,242.12,0.00,4.7,107,329,0.61,2.01,19.91
2,15-05-2024,StyleHub Shoes Pro,3,48.82,42.43,9.86,4.1,256,342,0.29,0.99,6.39
3,23-01-2025,TechPro Headphones Standard,1,2401.75,2196.13,0.00,4.1,117,174,0.57,0.99,205.62
4,2024-03-04 00:00:00,StoryWorld Children Pro,5,50.58,45.79,0.00,4.7,366,357,0.28,1.00,4.79

In [11]:
df['date'] = pd.to_datetime(df['date'])

In [12]:
def get_season(month):
    
    if month in [12,1,2]:
        return "Winter"
    
    elif month in [3,4,5]:
        return "Summer"
    
    elif month in [6,7,8,9]:
        return "Monsoon"
    
    else:
        return "Autumn"


df['season'] = df['date'].dt.month.apply(get_season)

In [13]:
df[['date','season']].head()

        date  season
0 2024-05-10  Summer
1 2024-10-06  Autumn
2 2024-05-15  Summer
3 2025-01-23  Winter
4 2024-03-04  Summer

In [14]:
df = df[df['amazon_price'] < 10000]
df = df[df['meesho_price'] < 10000]

In [15]:
df_final = df[[
    'product_name',
    'amazon_price',
    'meesho_price',
    'discount_pct',
    'rating',
    'num_reviews',
    'page_views',
    'conversion_rate',
    'demand_intensity',
    'season',
    'price_difference'
]]

In [16]:
df_final.head(10)

,product_name,amazon_price,meesho_price,discount_pct,rating,num_reviews,page_views,conversion_rate,demand_intensity,season,price_difference
0,SmartGen Headphones Plus,2236.79,2100.72,0.00,3.6,66,69,4.35,3.00,Summer,136.07
1,UrbanWear Shoes Premium,262.03,242.12,0.00,4.7,107,329,0.61,2.01,Autumn,19.91
2,StyleHub Shoes Pro,48.82,42.43,9.86,4.1,256,342,0.29,0.99,Summer,6.39
3,TechPro Headphones Standard,2401.75,2196.13,0.00,4.1,117,174,0.57,0.99,Winter,205.62
4,StoryWorld Children Pro,50.58,45.79,0.00,4.7,366,357,0.28,1.00,Summer,4.79
5,TrendSet Jeans Standard,355.44,324.01,0.00,4.2,226,260,0.38,0.99,Autumn,31.43
6,ClassicPress Non-Fiction Pro,38.71,34.70,9.60,4.5,125,490,0.41,2.01,Winter,4.01
7,ModernSpace Decor Premium,382.06,349.96,0.00,4.4,355,254,0.79,2.01,Winter,32.10
8,KitchenPro Decor Plus,210.59,192.07,0.00,4.3,138,63,3.17,2.00,Winter,18.52
9,SmartGen Headphones Plus,2177.01,1932.65,0.00,3.6,66,301,0.33,0.99,Autumn,244.36

In [17]:
df_final.describe()

,amazon_price,meesho_price,discount_pct,rating,num_reviews,page_views,conversion_rate,demand_intensity,price_difference
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000,5000.000000,5000.000000
mean,527.971428,483.570764,2.995692,4.278300,242.31360,272.932000,0.932696,1.805428,44.400664
std,658.905446,604.751128,6.543632,0.395149,135.05157,131.729009,0.863039,0.900324,63.509718
min,11.220000,10.470000,0.000000,3.600000,10.00000,50.000000,0.200000,0.980000,0.300000
25%,65.762500,60.005000,0.000000,4.000000,125.00000,157.000000,0.400000,1.000000,5.180000
50%,257.335000,232.230000,0.000000,4.300000,226.00000,272.000000,0.650000,1.990000,16.795000
75%,593.650000,545.220000,0.000000,4.600000,355.00000,387.250000,1.140000,2.010000,51.840000
max,2417.940000,2323.070000,24.970000,5.000000,498.00000,500.000000,7.840000,6.010000,343.490000

In [18]:
df_final.to_csv("final_dynamic_pricing_dataset.csv", index=False)

In [20]:
df_final.shape

(5000, 11)